# Generated by Django 5.2.1 on 2025-06-03 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vue', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['enseignant', 'parent', 'eleve']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='base.utilisateur')),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.eleve')),
            ],
        ),
    ]
