# Generated by Django 5.2.1 on 2025-06-03 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('coefficient', models.FloatField()),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres_affectations', to='base.classe')),
                ('enseignants', models.ManyToManyField(blank=True, limit_choices_to={'role': 'enseignant'}, related_name='matieres_affectations', to='base.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='EleveClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.classe')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, to='base.utilisateur')),
            ],
            options={
                'unique_together': {('eleve', 'classe')},
            },
        ),
    ]
