# Generated by Django 5.2.1 on 2025-06-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affectations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EleveClasse',
        ),
    ]
